### ISSUE TITLE
Links have to have https://, http://, or // infront of them

### ISSUE THREAD

**Issue by Steve0Greatness** [JaydenDev/MyScratchPage#4]
https://github.com/JaydenDev/MyScratchPage/blob/c52c011c81b018a4f3a0381b61e699aaa8679b4e/index.html#L54
The link(above) does not work. What it's linking to is `[current page]/aviateapp.eu.org` and not `https://aviateapp.eu.org`

**Comment by JaydenDev** [comment]
> https://github.com/JaydenDev/MyScratchPage/blob/c52c011c81b018a4f3a0381b61e699aaa8679b4e/index.html#L54
> 
> 
> The link(above) does not work. What it's linking to is `[current page]/aviateapp.eu.org` and not `https://aviateapp.eu.org`

That popup is commented out anyway, haven't removed it yet. If I do by some chance not remove it I'll fix this.
